server:
  port: 8762

spring:
  datasource:
    url: jdbc:postgresql://localhost:5442/auth_service
    username: user_giash
    password: nE5kMc7JCGNqwDQM
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
